### PR TITLE
Add forward-compatibility for new Beet versions

### PR DESCRIPTION
**Pull request by Luexa**
This PR changes the dependency specifications for Beet and related libraries to use `>=` constraints instead of `^` to allow users who consume `smithed-libraries` as a library to use newer Beet versions. The lock format now uses the `1.3.x` poetry format but the GitHub action uses `1.2.2` which is forward-compatible with this format so it should be fine. Additionally, missing `run` subcommands have been added to a couple functions to avoid errors with the current Mecha version.

Note that this PR does not update Beet, Mecha, etc. so GitHub actions should generate the same result as before. A new version is probably necessary for PyPI, but idk how to handle that.

### CODE REVIEW

**Comment by RitikShah** [comment]
Hmm, i'm not sure what u mean that `run` needs to be included, the latest versions of `bolt` allows for implicit `run`s?

**Comment by Luexa** [comment]
When I did `poetry update` and then tried to build, it errored due to
missing `run` in the locations I changed.

**Comment by vberlier** [comment]
The latest command tree includes `execute summon` which means that to access the normal `summon` command behind execute you now need to use `run` explicitly.

**Comment by RitikShah** [comment]
> The latest command tree includes `execute summon` which means that to access the normal `summon` command behind execute you now need to use `run` explicitly.

ahh, this makes a ton of sense 🤔

**Pull request merged**
