### PR TITLE
feat(crafter + custom_block): update to 1.20.5

### PR DESCRIPTION
**Pull request by edayot**
This PR is huge, a lot of files have changed
- It's based on #42 (the custom-block one is faster to review)
- be compatible with the new `minecraft:max_damage` & `minecraft:damage` item components
- Replacing the trick `execute store result (...) run data get ... 1.00001`, because it wasn't working fine
- using components everywhere

I'm not sure of everything I have done, it seems to work in my testing, but some behavior could have changed. 

(i also deleted my plugin for the item list, it's not needed anymore)

### CODE REVIEW

**Comment by RitikShah** [comment]
❤️ means so much. will get these reviewed soon!

**Comment by edayot** [comment]
Also, idk if I should add [this commit](https://github.com/edayot/Libraries/commit/8ecc259b5af035723532c2ce29c7a96e50dfa2a5), it adds auto-generated commands for default item components & default items tags.

Theses changes are more a feature requests, than an update so idk

**Comment by RitikShah** [comment]
@edayot Do u have a test pack to help us validate this?

**Comment by edayot** [comment]
Ok this is the test datapack : 
[test_dp.zip](https://github.com/Smithed-MC/Libraries/files/15209194/test_dp.zip)

This add test functions for smithed.crafter or smithed.custom_block
`function example:custom_block/give` : Give a custom_block

Crafts :
- 1 stick + 2 diamond_block in a sword shape (simple shaped)
- the vanilla cake recipe (test milk_bucket advanced remove)
- shapeless flint_and_steel recipe (simple shapeless)
- shapeless gravel + shears (test tools advanced remove)

**Comment by edayot** [comment]
Up !
Also idk if i should merge [this branch](https://github.com/edayot/Libraries/compare/1.20.5-crafter...edayot:Libraries:1.20.5-crafter-auto-generated), it auto generates a bunch of things that are not possible to know at run time.

**Review by TheNuclearNexus — APPROVED** [review]

**Pull request merged**
